env:
  browser: true
  es6: true
extends:
  - airbnb
  - airbnb/hooks
  - react-app
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  react/prop-types: 0
  no-underscore-dangle: 0
  quotes: ["error", "backtick"]
  object-curly-spacing: ["error", "never"]
  quote-props: ["error", "consistent"]
  max-len: ["error", { "code": 125 }]
  object-curly-newline: ["error", { "consistent": true }]
  react/jsx-closing-bracket-location: [0, "props-aligned"]
  react/jsx-props-no-spreading: [0, "explicitSpread"]
  no-shadow: 0


